<?php

namespace ContainerVk2NYnE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JyNxg3aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jyNxg3a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jyNxg3a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.api_refresh_token' => ['privates', 'debug.security.event_dispatcher.api_refresh_token', 'getDebug_Security_EventDispatcher_ApiRefreshTokenService', true],
            'security.event_dispatcher.main' => ['privates', 'debug.security.event_dispatcher.main', 'getDebug_Security_EventDispatcher_MainService', true],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.api_refresh_token' => '?',
            'security.event_dispatcher.main' => '?',
        ]);
    }
}
