<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'categoriems' => [parent::class, 'categoriems', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'examenresultats' => [parent::class, 'examenresultats', null],
        "\0".parent::class."\0".'examentests' => [parent::class, 'examentests', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'medicaments' => [parent::class, 'medicaments', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'ordonances' => [parent::class, 'ordonances', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'patients' => [parent::class, 'patients', null],
        "\0".parent::class."\0".'rendezvouses' => [parent::class, 'rendezvouses', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null],
        "\0".parent::class."\0".'vitals' => [parent::class, 'vitals', null],
        'adresse' => [parent::class, 'adresse', null],
        'categoriems' => [parent::class, 'categoriems', null],
        'created_at' => [parent::class, 'created_at', null],
        'email' => [parent::class, 'email', null],
        'examenresultats' => [parent::class, 'examenresultats', null],
        'examentests' => [parent::class, 'examentests', null],
        'id' => [parent::class, 'id', null],
        'medicaments' => [parent::class, 'medicaments', null],
        'nom' => [parent::class, 'nom', null],
        'ordonances' => [parent::class, 'ordonances', null],
        'password' => [parent::class, 'password', null],
        'patients' => [parent::class, 'patients', null],
        'rendezvouses' => [parent::class, 'rendezvouses', null],
        'roles' => [parent::class, 'roles', null],
        'tel' => [parent::class, 'tel', null],
        'vitals' => [parent::class, 'vitals', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
