<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Examentest extends \App\Entity\Examentest implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'date_test' => [parent::class, 'date_test', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'maladie' => [parent::class, 'maladie', null],
        "\0".parent::class."\0".'nom_patient' => [parent::class, 'nom_patient', null],
        "\0".parent::class."\0".'nom_test' => [parent::class, 'nom_test', null],
        "\0".parent::class."\0".'patient' => [parent::class, 'patient', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'created_at' => [parent::class, 'created_at', null],
        'date_test' => [parent::class, 'date_test', null],
        'id' => [parent::class, 'id', null],
        'maladie' => [parent::class, 'maladie', null],
        'nom_patient' => [parent::class, 'nom_patient', null],
        'nom_test' => [parent::class, 'nom_test', null],
        'patient' => [parent::class, 'patient', null],
        'user' => [parent::class, 'user', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
