<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM54UT0m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM54UT0m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM54UT0m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM54UT0m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM54UT0m\App_KernelDevDebugContainer([
    'container.build_hash' => 'M54UT0m',
    'container.build_id' => 'f01abc7e',
    'container.build_time' => 1688374336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM54UT0m');
