<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwuIOxI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwuIOxI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwuIOxI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwuIOxI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEwuIOxI\App_KernelDevDebugContainer([
    'container.build_hash' => 'EwuIOxI',
    'container.build_id' => 'b2455552',
    'container.build_time' => 1688307438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwuIOxI');
