<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6sE7GE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6sE7GE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6sE7GE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6sE7GE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6sE7GE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z6sE7GE',
    'container.build_id' => '79e9e182',
    'container.build_time' => 1688827981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6sE7GE');
